word_list = words = ["motorcycle",
                     "aston martin",
                     "jeep",
                     "volkswagen",
                     "yamaha",
                     "triumph",
                     "audi",
                     "tesla",
                     "mitsubishi",
                     "hyundai",
                     "aerodynamics",
                     "algorithm",
                     "javascript",
                     "database",
                     "programming",
                     "sustainability",
                     "negotiation",
                     "ambition",
                     "strategy",
                     "marketing"]